### PR TITLE
Nl design edits

### PR DESCRIPTION
**Pull request by lh1008**
Hi krista,

I did this PR so you are able to check and verify the edits I made to the files. You will see that the translation was already added to the printer-friendly version. I also exported it as pdf's siles, so you can also see that those files have been changed. This PR adds a lot of commits to your master branch becuase like I told you in the chat, you are behind some of them, so If you decide to merge the PR totally that will help you update some of the commits from the original https://github.com/monero-ecosystem/outreach-docs repo.

If you have any questions, let me know. 

Thank you for all your work and effort.

### CODE REVIEW

**Comment by erciccione** [comment]
@lh1008 This PR is not needed since @krista89 's files don't create any conflict. I think it just confuses things.

**Comment by erciccione** [comment]
Ok i noticed now that the folder was removed, but i still suggest to not open a Pul Request this way when the workflow is not clear to the contributor @lh1008

**Comment by lh1008** [comment]
Ok @erciccione, thank you for the clarification. I did the PR because I was sharing @krista89 the "final" design and also wanted her to check some of the translations that were missing. I'll be closing the PR, and let her do the PR to the monero-ecosystem. 

Thanks :)

**Comment by erciccione** [comment]
Sorry for the double correction, but i checked deeply and i confirm. This PR was unnecessary, there are no conflicts with the main branch and she can open the PR directly on the official monero-outreach. Chatting with her right now btw

**Comment by lh1008** [comment]
It's ok.

**Pull request closed without merging**
